export const CATS={pos:"Pozitív jellem",neg:"Negatív jellem",emo:"Érzések, állapot",work:"Munka, interjú",day:"Hétköznapi",qa:"Tesztelés, SDET"};
export const W=[
["kind","kedves","She's very kind to everyone.","pos"],
["nice","kedves, jó fej","Your neighbour seems really nice.","pos"],
["friendly","barátságos","The people there are friendly.","pos"],
["honest","őszinte","To be honest, I don't like it.","pos"],
["reliable","megbízható","He's reliable, he always delivers.","pos"],
["patient","türelmes","You have to be patient with kids.","pos"],
["hardworking","szorgalmas","My team is very hardworking.","pos"],
["funny","vicces","He's really funny.","pos"],
["smart","okos","My daughter is very smart.","pos"],
["calm","nyugodt","Stay calm, it's fine.","pos"],
["confident","magabiztos","I feel confident about the interview.","pos"],
["helpful","segítőkész, hasznos","Thanks, that was really helpful.","pos"],
["polite","udvarias","Be polite to the customer.","pos"],
["generous","nagylelkű","He's generous with his time.","pos"],
["cheerful","vidám","She's always cheerful in the morning.","pos"],
["easygoing","laza, könnyed","My boss is quite easygoing.","pos"],
["open-minded","nyitott","Try to be open-minded.","pos"],
["brave","bátor","That was a brave decision.","pos"],
["thoughtful","figyelmes","What a thoughtful gift!","pos"],
["curious","kíváncsi","Kids are naturally curious.","pos"],
["lazy","lusta","I'm too lazy to cook today.","neg"],
["rude","bunkó, udvariatlan","That waiter was so rude.","neg"],
["selfish","önző","Don't be selfish, share it.","neg"],
["stubborn","makacs","My son is very stubborn.","neg"],
["arrogant","beképzelt, arrogáns","He's smart but arrogant.","neg"],
["moody","szeszélyes, hangulatingadozós","She's moody before lunch.","neg"],
["impatient","türelmetlen","Don't be so impatient.","neg"],
["bossy","parancsolgató","My sister is a bit bossy.","neg"],
["shy","félénk","He's shy with new people.","neg"],
["clumsy","ügyetlen","I'm so clumsy, I broke a glass.","neg"],
["grumpy","morcos","He's grumpy without coffee.","neg"],
["careless","hanyag, figyelmetlen","It was a careless mistake.","neg"],
["unreliable","megbízhatatlan","The bus is so unreliable.","neg"],
["jealous","féltékeny","He's jealous of his brother.","neg"],
["mean","szemét, rosszindulatú","That was a mean thing to say.","neg"],
["strict","szigorú","My old manager was very strict.","neg"],
["silly","buta, butus","Don't be silly, it's fine.","neg"],
["greedy","kapzsi","Don't be greedy.","neg"],
["tired","fáradt","I'm tired after work.","emo"],
["exhausted","kimerült","With three kids, I'm exhausted.","emo"],
["worried","aggódó","I'm worried about money.","emo"],
["nervous","izgul, ideges","I'm always nervous before interviews.","emo"],
["angry","dühös","He was angry about the mistake.","emo"],
["upset","felzaklatott","She was upset about the news.","emo"],
["stressed","stresszes","I'm a bit stressed this week.","emo"],
["frustrated","frusztrált, elkeseredett","I'm frustrated with the job market.","emo"],
["overwhelmed","túlterhelt, elárasztott","I feel overwhelmed right now.","emo"],
["relieved","megkönnyebbült","I was relieved when it worked.","emo"],
["excited","izgatott, lelkes","I'm excited about the new job.","emo"],
["surprised","meglepett","I was surprised by the offer.","emo"],
["bored","unatkozik","The kids are bored.","emo"],
["annoyed","bosszús","I'm annoyed with the delay.","emo"],
["proud","büszke","I'm proud of my kids.","emo"],
["scared","megijedt, fél","She's scared of dogs.","emo"],
["embarrassed","zavarban van","I was so embarrassed.","emo"],
["disappointed","csalódott","I'm disappointed with the result.","emo"],
["grateful","hálás","I'm grateful for your help.","emo"],
["lonely","magányos","He feels lonely at home.","emo"],
["confused","összezavarodott","Sorry, I'm confused.","emo"],
["experienced","tapasztalt","I'm experienced in test automation.","work"],
["familiar","ismerős, jártas","I'm familiar with Playwright and TypeScript.","work"],
["responsible","felelős","I was responsible for the test framework.","work"],
["detail-oriented","precíz, a részletekre figyel","As a tester, I'm very detail-oriented.","work"],
["proactive","proaktív","I try to be proactive, not reactive.","work"],
["organized","szervezett","I keep my tasks organized.","work"],
["flexible","rugalmas","I'm flexible with working hours.","work"],
["adaptable","alkalmazkodó","I'm adaptable to new tools.","work"],
["independent","önálló","I'm independent and need little supervision.","work"],
["motivated","motivált","I'm highly motivated to learn.","work"],
["analytical","elemző","Testing needs an analytical mind.","work"],
["accurate","pontos","The test results must be accurate.","work"],
["efficient","hatékony","The new process is more efficient.","work"],
["skilled","képzett, ügyes","She's a skilled developer.","work"],
["ambitious","törekvő, ambiciózus","She has ambitious plans.","work"],
["supportive","támogató","My last team was very supportive.","work"],
["available","elérhető, ráér","Are you available on Monday?","work"],
["challenging","kihívást jelentő","It was a challenging project.","work"],
["demanding","megterhelő, igényes","The client was very demanding.","work"],
["straightforward","egyszerű, egyértelmű","The task was straightforward.","work"],
["busy","elfoglalt","I'm busy right now.","day"],
["useful","hasznos","This tool is really useful.","day"],
["useless","haszontalan","This app is useless.","day"],
["difficult","nehéz","It's a difficult situation.","day"],
["similar","hasonló","The two jobs are similar.","day"],
["necessary","szükséges","Is that really necessary?","day"],
["obvious","nyilvánvaló","The answer is obvious.","day"],
["fair","igazságos, korrekt","That's not fair!","day"],
["tough","kemény, nehéz","It's a tough market.","day"],
["expensive","drága","Petrol is expensive.","day"],
["cheap","olcsó","This phone was really cheap.","day"],
["comfortable","kényelmes","These shoes are comfortable.","day"],
["awkward","kínos, suta","That was an awkward moment.","day"],
["annoying","idegesítő","This noise is annoying.","day"],
["boring","unalmas","The meeting was boring.","day"],
["weird","fura","That's weird.","day"],
["quiet","csendes","It's a quiet village.","day"],
["noisy","zajos","The kids are so noisy today.","day"],
["crowded","zsúfolt","The shop was crowded.","day"],
["messy","rendetlen","The kids' room is messy.","day"],
["tidy","rendes, rendezett","Keep your desk tidy.","day"],
["flaky","instabil (hol átmegy, hol elbukik)","How do you deal with flaky tests?","qa"],
["intermittent","időszakos, nem mindig jelentkező","The failure is intermittent, so we need more logs to find it.","qa"],
["reproducible","reprodukálható","Is the bug reproducible, or did it happen only once?","qa"],
["reproduce","reprodukál, újra előidéz","Can you reproduce the issue on the test environment?","qa"],
["root cause","kiváltó ok","What was the root cause of the production incident?","qa"],
["edge case","határeset","Which edge case would you test first here?","qa"],
["requirement","követelmény","What do you do when a requirement is unclear?","qa"],
["acceptance criteria","elfogadási feltételek","Who writes the acceptance criteria in your team?","qa"],
["coverage","lefedettség","Code coverage alone doesn't tell you the quality of the tests.","qa"],
["maintainable","karbantartható","How do you keep a large test suite maintainable?","qa"],
["scalable","skálázható","Is your framework scalable to more teams and projects?","qa"],
["robust","robusztus, strapabíró","We need robust locators that don't break after every UI change.","qa"],
["deterministic","determinisztikus, mindig ugyanazt adja","A test should be deterministic: same input, same result.","qa"],
["isolated","elszigetelt, független","Tests should be isolated, so they can run in any order.","qa"],
["verify","ellenőriz","How do you verify that the API returns the correct data?","qa"],
["investigate","kivizsgál, utánajár","How do you investigate a failed test in the pipeline?","qa"],
["prioritize","priorizál, fontossági sorrendet állít","How do you prioritize what to automate first?","qa"],
["estimate","becslés, megbecsül","Can you give an estimate for the regression testing?","qa"],
["stakeholder","érintett, érdekelt fél","How do you report test results to a non-technical stakeholder?","qa"],
["trade-off","kompromisszum, mérlegelés","What's the trade-off between UI tests and API tests?","qa"],
["bottleneck","szűk keresztmetszet","Testing shouldn't be the bottleneck before a release.","qa"],
["severity","súlyosság","What's the difference between severity and priority?","qa"],
["workaround","kerülőmegoldás","Is there a workaround until the fix is deployed?","qa"],
["deadline","határidő","What do you do if testing isn't finished before the deadline?","qa"],
["assumption","feltételezés","Don't build a test on an assumption, ask the product owner.","qa"],
["environment","környezet","Why does the test pass locally but fail in another environment?","qa"],
["thorough","alapos","We need a thorough review of the payment flow.","qa"],
["consistent","következetes, egységes","The test results are not consistent between runs.","qa"],
["outdated","elavult","The documentation was outdated, so I checked the code.","qa"],
["redundant","felesleges, duplikált","If two tests check the same thing, one of them is redundant.","qa"],
["time-consuming","időigényes","Manual regression is time-consuming, so we automated it.","qa"],
["cross-functional","több szakterületet átfogó","Have you worked in a cross-functional team before?","qa"],
["ownership","felelősségvállalás, gazdája valaminek","In our team, developers take ownership of quality too.","qa"],
["improvement","javulás, fejlesztés","What improvement would you make to our test process?","qa"],
["reduce","csökkent","How would you reduce the execution time of the test suite?","qa"],
["implement","bevezet, megvalósít","How would you implement a test strategy from scratch?","qa"],
["mentor","mentorál","Would you be willing to mentor junior testers?","qa"]
];